### ISSUE TITLE
Using Parse SDK

### ISSUE THREAD

**Issue by RamiJemli** [VictorAlbertos/RestAPIParseAuthCleanAndroid#1]
I know that Parse Android SDK is doing a lot of work under the hood like caching and encrypting data. Is it really stable to use its synchronous calls with RxJava's Schedulers?
Retrofit works well with RxJava. But, why didn't you use Parse's sdk ? 
Should I drop the SDK and use their REST API instead just like you did in your implementation ?

**Comment by VictorAlbertos** [comment]
Well, I did it because I don't like the idea of being subordinated to the architecture derived from this SDK. 

Plus, with this approach Parse just provide a backend, so if i need to switch to another backend-solution, I don't need to refactor my project. I don't use Parse usually, in fact, most of the time I work with apis developed by my coworkers

But it's up to you ;)
